# Generated by Django 4.2.4 on 2023-08-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forwarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deleted', models.DateTimeField()),
                ('from_chat', models.CharField(blank=True, default='', max_length=100)),
                ('to_chats', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
