# Generated by Django 4.2.4 on 2023-08-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
