# Generated by Django 4.2.4 on 2023-08-27 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_alter_forwarding_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tagger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('teggees', models.CharField(blank=True, default='', max_length=1000)),
            ],
        ),
    ]
