# Generated by Django 4.2.4 on 2023-08-27 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_tagger'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tagger',
            options={'ordering': ['created']},
        ),
    ]
