# Generated by Django 4.2.4 on 2023-08-27 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_alter_tagger_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tagger',
            old_name='teggees',
            new_name='taggees',
        ),
    ]
