# Generated by Django 4.2.4 on 2023-08-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_rename_teggees_tagger_taggees'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagGroups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('taggees', models.CharField(blank=True, default='', max_length=1000)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RenameModel(
            old_name='Tagger',
            new_name='TagForwarding',
        ),
        migrations.RenameField(
            model_name='tagforwarding',
            old_name='taggees',
            new_name='to_chats',
        ),
    ]
