# Generated by Django 4.2.4 on 2023-08-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_taggroups_rename_tagger_tagforwarding_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggroups',
            old_name='taggees',
            new_name='usernames',
        ),
    ]
