# Generated by Django 4.2.4 on 2023-09-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_rename_taggees_taggroups_usernames'),
    ]

    operations = [
        migrations.AddField(
            model_name='tagforwarding',
            name='allowed_users',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
