# Generated by Django 4.2.4 on 2023-09-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_alter_forwarding_from_chat_alter_forwarding_to_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='from_chat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='forwarding',
            name='to_chats',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='to_chats',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='usernames',
            field=models.CharField(max_length=1000),
        ),
    ]
