# Generated by Django 4.2.4 on 2023-09-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_alter_forwarding_from_chat_alter_forwarding_to_chats_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='from_chat',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='forwarding',
            name='to_chats',
            field=models.JSONField(),
        ),
    ]
