# Generated by Django 4.2.4 on 2023-09-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_alter_forwarding_from_chat_alter_forwarding_to_chats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagforwarding',
            name='allowed_users',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='tag',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='to_chats',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='tag',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='usernames',
            field=models.JSONField(),
        ),
    ]
