# Generated by Django 4.2.4 on 2023-09-03 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_alter_tagforwarding_allowed_users_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwarding',
            name='from_chat',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='allowed_users',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='tagforwarding',
            name='tag',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='taggroups',
            name='tag',
            field=models.CharField(max_length=1000),
        ),
    ]
