# Generated by Django 4.2.4 on 2023-09-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_alter_forwarding_from_chat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagforwarding',
            name='allowed_users',
            field=models.JSONField(),
        ),
    ]
