# Generated by Django 4.2.4 on 2023-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_chatswithbot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatswithbot',
            name='chat_id',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
